# Generated by Django 3.1 on 2020-08-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='yok', max_length=50),
            preserve_default=False,
        ),
    ]
